/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../../shared/model/cabinet-api-types.generated';

import { cabinetApi } from '@shared/api/cabinet-api';
export type SignInMutationVariables = Types.Exact<{
  password: Types.Scalars['String']['input'];
  email: Types.Scalars['String']['input'];
}>;


export type SignInMutation = { __typename?: 'Mutation', signIn: { __typename?: 'TokensObjectType', accessToken: string, refreshToken: string } };


export const SignInDocument = `
    mutation signIn($password: String!, $email: String!) {
  signIn(data: {password: $password, email: $email}) {
    accessToken
    refreshToken
  }
}
    `;

const injectedRtkApi = cabinetApi.injectEndpoints({
  endpoints: (build) => ({
    signIn: build.mutation<SignInMutation, SignInMutationVariables>({
      query: (variables) => ({ document: SignInDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useSignInMutation } = injectedRtkApi;

