/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../../shared/model/cabinet-api-types.generated';

import { cabinetApi } from '@shared/api/cabinet-api';
export type SignUpMutationVariables = Types.Exact<{
  email: Types.Scalars['String']['input'];
  password: Types.Scalars['String']['input'];
}>;


export type SignUpMutation = { __typename?: 'Mutation', signUp: { __typename?: 'User', id: number, email: string, isConfirmed: boolean } };


export const SignUpDocument = `
    mutation signUp($email: String!, $password: String!) {
  signUp(data: {email: $email, password: $password}) {
    id
    email
    isConfirmed
  }
}
    `;

const injectedRtkApi = cabinetApi.injectEndpoints({
  endpoints: (build) => ({
    signUp: build.mutation<SignUpMutation, SignUpMutationVariables>({
      query: (variables) => ({ document: SignUpDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useSignUpMutation } = injectedRtkApi;

